Repository Erik142/PasswordManager, pull requests merged in 2021-02, with the labels that each got.

#10 Implement communication protocol
  PasswordManager/src/passwordmanager/Credential.java
  PasswordManager/src/passwordmanager/UserAccount.java
  PasswordManager/src/passwordmanager/communication/AES.java
  PasswordManager/src/passwordmanager/communication/CommunicationEventListener.java
  PasswordManager/src/passwordmanager/communication/CommunicationProtocol.java
Labels: Implementation

#17 Added DB
  PasswordManager/.classpath
  PasswordManager/PasswordManagerDatabase.db
  PasswordManager/src/passwordmanager/PasswordDatabase.java
Labels: Implementation

#16 Initial implementation of PasswordServer listen and processClient methods
  PasswordManager/src/passwordmanager/PasswordServer.java
  PasswordManager/src/passwordmanager/PasswordServerDebug.java
  PasswordManager/src/passwordmanager/Program.java
  PasswordManager/src/passwordmanager/communication/CommunicationProtocol.java
  PasswordManager/src/passwordmanager/communication/PasswordServer.java
  PasswordManager/src/passwordmanager/config/Configuration.java
  PasswordManager/src/passwordmanager/util/StringExtensions.java
Labels: Implementation

#31 Make sure build does not break
  PasswordManager/src/passwordmanager/PasswordServerDebug.java
  PasswordManager/src/passwordmanager/communication/PasswordServer.java
Labels: bug

#29 Convert to maven project, improve protocol encryption and implement query/response system
  PasswordManager/.classpath
  PasswordManager/.gitignore
  PasswordManager/.gradle/6.3/executionHistory/executionHistory.bin
  PasswordManager/.gradle/6.3/executionHistory/executionHistory.lock
  PasswordManager/.gradle/6.3/fileChanges/last-build.bin
  PasswordManager/.gradle/6.3/fileContent/fileContent.lock
  PasswordManager/.gradle/6.3/fileHashes/fileHashes.bin
  PasswordManager/.gradle/6.3/fileHashes/fileHashes.lock
  PasswordManager/.gradle/6.3/gc.properties
  PasswordManager/.gradle/6.3/javaCompile/classAnalysis.bin
  PasswordManager/.gradle/6.3/javaCompile/javaCompile.lock
  PasswordManager/.gradle/6.3/javaCompile/taskHistory.bin
  PasswordManager/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  PasswordManager/.gradle/buildOutputCleanup/cache.properties
  PasswordManager/.gradle/buildOutputCleanup/outputFiles.bin
  PasswordManager/.gradle/checksums/checksums.lock
  PasswordManager/.gradle/checksums/md5-checksums.bin
  PasswordManager/.gradle/checksums/sha1-checksums.bin
  PasswordManager/.gradle/vcs-1/gc.properties
  PasswordManager/.project
  PasswordManager/.settings/org.eclipse.jdt.core.prefs
  PasswordManager/.settings/org.eclipse.m2e.core.prefs
  PasswordManager/pom.xml
  PasswordManager/run-configs/PasswordManager.launch
  PasswordManager/src/passwordmanager/PasswordServerDebug.java
  PasswordManager/src/passwordmanager/Program.java
  PasswordManager/src/passwordmanager/communication/AES.java
  PasswordManager/src/passwordmanager/communication/CommunicationProtocol.java
  PasswordManager/src/passwordmanager/communication/Message.java
  PasswordManager/src/passwordmanager/communication/PasswordServer.java
  PasswordManager/src/passwordmanager/communication/Query.java
  PasswordManager/src/passwordmanager/communication/RSA.java
  PasswordManager/src/passwordmanager/communication/Response.java
  PasswordManager/src/passwordmanager/config/Configuration.java
Labels: enhancement

#40 Ensure that master branch builds
  PasswordManager/src/passwordmanager/PasswordGenerator.java
Labels: bug, high priority

#48 Implement forgot password functionality
  PasswordManager/pom.xml
  PasswordManager/src/passwordmanager/PasswordDatabase.java
  PasswordManager/src/passwordmanager/Program.java
  PasswordManager/src/passwordmanager/communication/CommunicationEventListener.java
  PasswordManager/src/passwordmanager/communication/CommunicationProtocol.java
  PasswordManager/src/passwordmanager/communication/Message.java
  PasswordManager/src/passwordmanager/communication/PasswordServer.java
  PasswordManager/src/passwordmanager/communication/Query.java
  PasswordManager/src/passwordmanager/communication/Response.java
  PasswordManager/src/passwordmanager/config/Configuration.java
  PasswordManager/src/passwordmanager/util/EmailUtil.java
  PasswordManager/src/passwordmanager/util/StringExtensions.java
Labels: Implementation, enhancement

#46 Add database interaction to the password server
  PasswordManager/src/passwordmanager/PasswordDatabase.java
  PasswordManager/src/passwordmanager/PasswordServerDebug.java
  PasswordManager/src/passwordmanager/Program.java
  PasswordManager/src/passwordmanager/communication/CommunicationProtocol.java
  PasswordManager/src/passwordmanager/communication/PasswordServer.java
Labels: enhancement

#56 Create docker-publish.yml
  .github/workflows/docker-publish.yml
Labels: enhancement

#61 Implement ForgotPasswordController and LoginScreenController
  PasswordManager/src/passwordmanager/ForgotPasswordDialog.java
  PasswordManager/src/passwordmanager/ForgotPasswordDialogController.java
  PasswordManager/src/passwordmanager/LoginScreen.java
  PasswordManager/src/passwordmanager/LoginScreenController.java
  PasswordManager/src/passwordmanager/PasswordClient.java
  PasswordManager/src/passwordmanager/Program.java
Labels: Implementation
